[tools]
"ubi:leptos-rs/cargo-leptos" = "latest"
"ubi:bram209/leptosfmt" = "latest"
node = { version = "latest", postinstall = "corepack enable" }

[tasks.update-scripts]
run = "chmod -R +x mise-tasks/"
description = "Update scripts execution permissions defined in mise-tasks"
sources = ["mise-tasks/**/*"]
