#!/usr/bin/env bash
#MISE description="Fix formatting in rust and cssfiles"
#MISE sources=["src/**/*.rs"]
#MISE outputs={auto=true}
echo "Fixing rust formatting"
cargo fmt
echo && echo "Fixing rstml formatting"
leptosfmt ./src
echo && echo "Fixing CSS formatting"
biome format --fix
