#!/usr/bin/env bash
#MISE description="Fix linting errors in rust and css files"
#MISE sources=["src/**/*.rs"]
#MISE outputs={auto=true}
cargo clippy --no-deps --all-targets --all-features --fix
biome lint --fix
