name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

env:
  MISE_EXPERIMENTAL: true
  RUSTFLAGS: "-Dwarnings -Z threads=4"

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Setup mold linker for faster builds
        uses: rui314/setup-mold@v1

      - name: Install minimal needed rust toolchain
        run: rustup toolchain install --profile minimal

      - name: Install rustup CI components
        run: rustup component add clippy rustfmt

      - name: setup caching for debug build
        uses: Swatinem/rust-cache@v2

      - name: Install mise tools
        uses: jdx/mise-action@v2
        with:
          experimental: true
          log_level: debug

      - name: Check formatting
        run: mise run format

      - name: Check linting
        run: mise run lint

      - name: Build application in debug mode (for speed)
        run: mise run build
