name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

env:
  MISE_EXPERIMENTAL: true
  RUSTFLAGS: "-Dwarnings -Z threads=4"

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Setup mold linker for faster builds
        uses: rui314/setup-mold@v1

      - name: Setup Rust toolchain with cargo caching (no rustup caching)
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install mise and tools with caching
        uses: jdx/mise-action@v2
        with:
          experimental: true
          log_level: debug

      #   uses: actions/cache@v4
      # - name: Cache rust toolchain paths
      #   id: cache
      #   with:
      #     path: |
      #       ~/.rustup/
      #     restore-keys: ${{ runner.os }}-rustup-
      #     key: ${{ runner.os }}-rustup-${{ hashFiles('**/rust-toolchain.toml') }}

      # - name: Update rustup toolchain
      #   run: rustup component add rustfmt clippy
      #
      # - name: Check formatting
      #   run: mise run format
      #
      # - name: Check linting
      #   run: mise run lint
      #
      # - name: Build application in debug mode (for speed)
      #   run: mise run build

      - run: mise run build:release
